[project]
name = "sparv-sbx-superlim"
version = "0.1.0"
description = "A Sparv plugin for classifying text using the Superlim baseline models "
readme = "README.md"
requires-python = ">=3.11,<3.14"
license = "GPL-3.0-only"
authors = [
  { name = "Felix Morger", email = "felix.morger@gu.se" },
  { name = "Språkbanken Text", email = "sbx-info@svenska.gu.se" }
]
entry-points."sparv.plugin" = { sbx_superlim = "sbx_superlim" }
dependencies = [
  "datasets>=2.20.0,<2.21",
  "setuptools>=80,<81",
  "sparv>=5.3.1",
  "transformers>=5.0.0rc3,<5.1",
]

[dependency-groups]
metadata = [
  "sparv-sbx-metadata",
]

[build-system]
requires = ["uv_build>=0.10,<0.11"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "sbx_superlim"
module-root = ""

[tool.uv.sources]
sparv-sbx-metadata = { git = "https://github.com/spraakbanken/sparv-sbx-metadata", tag = "v2.3.1" }
