metadata:
  id: corpora
  name:
    eng: corpora
    swe: korpora
  language: swe
  description:
    eng: Swedish political manifestos with Superlim annotations
    swe: Svenska valmanifest med Superlimannoteringar
import:
  source_dir: source
  importer: text_import:parse
export:
  default:
    - xml_export:pretty
    - sbx_superlim:predictions
  annotations:
    - <token>
    - <sentence>
    - <sentence>:sbx_superlim.absabank-imm.score
    - <sentence>:sbx_superlim.argumentation.stance
sbx_superlim:
  hf_model_path:
    absabank-imm: 'sbx/KB-bert-base-swedish-cased_absabank-imm'
    absabank-imm: 'sbx/KB-bert-base-swedish-argumentation_sent'
  hf_inference_args:
    batch_size: 32
